---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-aws-eks-github-actions
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatbot-aws-eks-github-actions
  template:
    metadata:
      labels:
        app: chatbot-aws-eks-github-actions
    spec:
      containers:
      - name: chatbot-aws-eks-github-actions
        image: zahidmahmood1995/next-frontend:latest1
        ports:
        - containerPort: 3000   # Use port 3000
        env:
        - name: BACKEND_URL
          value: "http://ae11ff36fe27b43f09987467e4252255-727837298.us-west-2.elb.amazonaws.com:8081"
---
apiVersion: v1
kind: Service
metadata:
  name: chatbot-aws-eks-github-actions-service
spec:
  selector:
    app: chatbot-aws-eks-github-actions
  ports:
  - protocol: TCP
    port: 80                 # Expose port 80
    targetPort: 3000
  type: LoadBalancer
