---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-python-aws-eks-github-actions
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatbot-python-aws-eks-github-actions
  template:
    metadata:
      labels:
        app: chatbot-python-aws-eks-github-actions
    spec:
      containers:
      - name: chatbot-python-aws-eks-github-actions
        image: zahidmahmood1995/python-backend
        ports:
        - containerPort: 8081   # Use port 3000

---
apiVersion: v1
kind: Service
metadata:
  name: chatbot-python-aws-eks-github-actions-service
spec:
  selector:
    app: chatbot-python-aws-eks-github-actions
  ports:
  - protocol: TCP
    port: 8081                 # Expose port 80
    targetPort: 8081
  type: LoadBalancer
