name: Code Build Workflow

on:
    push:
      branches: 
        - main
        
jobs:
  build:
    name: Build
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Docker build and push
        run: |
          docker build -t react-aws-eks-github-actions .
          docker tag react-aws-eks-github-actions zahidmahmood1995/react-aws-eks-github-actions:latest
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker push zahidmahmood1995/react-aws-eks-github-actions:latest
      
  
