name: Deploy To EKS

on:
    workflow_run:
      workflows: 
        - Code Build Workflow
      types:
        - completed
  
jobs:
    build:
      name: Docker Image Scan
      runs-on: self-hosted
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v2

        - name: Pull the Docker image
          run: docker pull zahidmahmood1995/react-aws-eks-github-actions:latest

  
        - name: Update kubeconfig
          run: aws eks --region us-west-2 update-kubeconfig --name EKS_cluster_codewithmuh
  
        - name: Deploy to EKS
          run: kubectl apply -f deployment-service.yml 
  
  
